package com.aaa.dao;

import com.aaa.entity.Product;
import com.aaa.entity.ProductExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Dec 18 14:38:19 CST 2018
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    List<Map> findAllByPage(Map amp);

//    List<Product> findSomeByPage(Map amp);

    int getTotal();

    int addProduct(Product product);

    List<Product> findMake();

    List<Product> findInteriorColor();

    List<Product> findBodyColor();

    List<Product> findTransmission();

    List<Product> findEngine();

    List<Product> findBody();

    List<Product> findType(Product product);

    List<Product> findLine(Product product);

    List<Product> findPstatus();

    int updateProduct(Map map);

    int delProduct(int del);

    Product findCheckBody(Product product);

    List<Product> findPstatusTwo(Product product);


    int getTotal(Map amp);

    List<Map<String,Object>> productCount(Map map);
}